version: "3"

services:
  db:
    build:
      context: "."
      dockerfile: "./docker/postgres.Dockerfile"
    volumes:
      - ./.db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - POSTGRES_HOST=${PG_HOST}
