@api = https://reedsemi.dev.lexionlu.xyz/sender/email

### GET ALL EMAIL
GET {{api}}

### CREATE AN EMAIL
POST {{api}}
Content-Type: application/json

{
    "send_from": "kayac",
    "address": "testm",
    "phone": "123456",
    "content": "test"
}